// Vendored from FoodDelivery/packages/fd_ui (FoodDeliveryAppDesignSystem).
// Do not edit here — re-copy from the source repo when the design system changes.

// GENERATED by tools/gen_tokens.mjs from design/tokens.json. Do not edit.

// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

/// Semantic colours for one theme. Read with `context.fd` (see theme.dart).
@immutable
class FdColors extends ThemeExtension<FdColors> {
  const FdColors({
    required this.grey0,
    required this.grey50,
    required this.grey100,
    required this.grey200,
    required this.grey400,
    required this.grey500,
    required this.grey700,
    required this.grey900,
    required this.grey1000,
    required this.background,
    required this.surface,
    required this.surfaceRaised,
    required this.surfaceSubtle,
    required this.surfacePressed,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.border,
    required this.borderStrong,
    required this.divider,
    required this.primary,
    required this.primaryPressed,
    required this.onPrimary,
    required this.disabled,
    required this.onDisabled,
    required this.focusRing,
    required this.overlay,
    required this.photoPlaceholder,
    required this.error,
    required this.errorPressed,
    required this.onError,
    required this.success,
    required this.warning,
  });

  /// Scale anchor = the page ground. Referenced by `background`.
  final Color grey0;
  /// Subtle fill: skeletons, photo placeholders, table header, hovered rows. Never put `error` text on it.
  final Color grey50;
  /// Pressed / hovered fills for ghost controls; disabled fills.
  final Color grey100;
  /// Hairline borders and dividers (decorative, non-interactive).
  final Color grey200;
  /// Interactive control borders (inputs, checkboxes, outline buttons). 3.2:1+ on background and grey-50 in both themes.
  final Color grey400;
  /// Tertiary text: captions, timestamps, helper text. 4.9:1+ on background and grey-50.
  final Color grey500;
  /// Secondary text: descriptions, metadata. 7:1+ on background and grey-50.
  final Color grey700;
  /// Pressed state of the primary fill.
  final Color grey900;
  /// Scale anchor = the ink. Referenced by `text-primary` and `primary`.
  final Color grey1000;
  /// Page / screen ground. Pure white in light, pure black in dark.
  final Color background;
  /// Cards, list rows, app bars: same as background, separated by a 1px `border`, never by fill.
  final Color surface;
  /// Bottom sheets, dialogs, menus, toasts. Same ground plus `border` and, in light only, `shadow-overlay`.
  final Color surfaceRaised;
  /// Quiet fill for skeletons, image placeholders, table headers, selected sidebar item, hover rows.
  final Color surfaceSubtle;
  /// Pressed / hover fill for ghost buttons, list rows, icon buttons.
  final Color surfacePressed;
  /// Headings, body, prices, labels. On background, surface, surface-raised, surface-subtle (19:1+).
  final Color textPrimary;
  /// Descriptions, metadata, inactive tabs. On background and surface-subtle (7:1+).
  final Color textSecondary;
  /// Captions, timestamps, helper text, placeholders. On background and surface-subtle (4.9:1+).
  final Color textTertiary;
  /// 1px hairlines around cards, sheets, tables and between rows. Decorative only.
  final Color border;
  /// 1px border of interactive controls: inputs, checkboxes, radios, outline buttons, chips (3:1+).
  final Color borderStrong;
  /// 1px separators inside lists and sections.
  final Color divider;
  /// Primary button fill, selected chip/segment, switch on, checked box, active tab indicator. Black in light, white in dark.
  final Color primary;
  /// Primary fill while hovered / pressed.
  final Color primaryPressed;
  /// Text and icons on `primary` and `primary-pressed` (15:1+).
  final Color onPrimary;
  /// Fill of disabled filled controls.
  final Color disabled;
  /// Text and icons on disabled controls; disabled borders. Exempt from contrast minimums by WCAG; always pair with a non-colour cue (no hover, not-allowed cursor).
  final Color onDisabled;
  /// 2px outline, offset 2px, on every focusable control. Ink on the page ground: 21:1.
  final Color focusRing;
  /// Scrim behind dialogs and bottom sheets.
  final Color overlay;
  /// Fill shown before / instead of food photography.
  final Color photoPlaceholder;
  /// The one red. Errors, validation, destructive actions, Rejected/Cancelled. 4.58:1 on pure white AND pure black; as text only on background / surface / surface-raised, never on surface-subtle.
  final Color error;
  /// Destructive button while hovered / pressed.
  final Color errorPressed;
  /// Text and icons on `error` fills (4.58:1) and `error-pressed` (5.8:1).
  final Color onError;
  /// Muted green for small success markers only: a dot, an icon, a word (Delivered, Online, In stock). 4.9:1+ on background and surface-subtle. Never a fill.
  final Color success;
  /// Muted amber for small warning markers only: late order, low stock, timer under 10s. 5.2:1+ on background and surface-subtle. Never a fill.
  final Color warning;

  static const light = FdColors(
    grey0: Color(0xFFFFFFFF),
    grey50: Color(0xFFF5F5F5),
    grey100: Color(0xFFEBEBEB),
    grey200: Color(0xFFD9D9D9),
    grey400: Color(0xFF8A8A8A),
    grey500: Color(0xFF6B6B6B),
    grey700: Color(0xFF525252),
    grey900: Color(0xFF262626),
    grey1000: Color(0xFF000000),
    background: Color(0xFFFFFFFF),
    surface: Color(0xFFFFFFFF),
    surfaceRaised: Color(0xFFFFFFFF),
    surfaceSubtle: Color(0xFFF5F5F5),
    surfacePressed: Color(0xFFEBEBEB),
    textPrimary: Color(0xFF000000),
    textSecondary: Color(0xFF525252),
    textTertiary: Color(0xFF6B6B6B),
    border: Color(0xFFD9D9D9),
    borderStrong: Color(0xFF8A8A8A),
    divider: Color(0xFFD9D9D9),
    primary: Color(0xFF000000),
    primaryPressed: Color(0xFF262626),
    onPrimary: Color(0xFFFFFFFF),
    disabled: Color(0xFFEBEBEB),
    onDisabled: Color(0xFFA3A3A3),
    focusRing: Color(0xFF000000),
    overlay: Color.fromRGBO(0, 0, 0, 0.48),
    photoPlaceholder: Color(0xFFF5F5F5),
    error: Color(0xFFE02D2D),
    errorPressed: Color(0xFFC42525),
    onError: Color(0xFFFFFFFF),
    success: Color(0xFF1D7A3E),
    warning: Color(0xFF8F5B00),
  );

  static const dark = FdColors(
    grey0: Color(0xFF000000),
    grey50: Color(0xFF141414),
    grey100: Color(0xFF1F1F1F),
    grey200: Color(0xFF2E2E2E),
    grey400: Color(0xFF6B6B6B),
    grey500: Color(0xFF8C8C8C),
    grey700: Color(0xFFB3B3B3),
    grey900: Color(0xFFD9D9D9),
    grey1000: Color(0xFFFFFFFF),
    background: Color(0xFF000000),
    surface: Color(0xFF000000),
    surfaceRaised: Color(0xFF000000),
    surfaceSubtle: Color(0xFF141414),
    surfacePressed: Color(0xFF1F1F1F),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFB3B3B3),
    textTertiary: Color(0xFF8C8C8C),
    border: Color(0xFF2E2E2E),
    borderStrong: Color(0xFF6B6B6B),
    divider: Color(0xFF2E2E2E),
    primary: Color(0xFFFFFFFF),
    primaryPressed: Color(0xFFD9D9D9),
    onPrimary: Color(0xFF000000),
    disabled: Color(0xFF1F1F1F),
    onDisabled: Color(0xFF5C5C5C),
    focusRing: Color(0xFFFFFFFF),
    overlay: Color.fromRGBO(0, 0, 0, 0.72),
    photoPlaceholder: Color(0xFF141414),
    error: Color(0xFFE02D2D),
    errorPressed: Color(0xFFC42525),
    onError: Color(0xFFFFFFFF),
    success: Color(0xFF4CBB6F),
    warning: Color(0xFFE0A423),
  );

  @override
  FdColors copyWith({Color? grey0, Color? grey50, Color? grey100, Color? grey200, Color? grey400, Color? grey500, Color? grey700, Color? grey900, Color? grey1000, Color? background, Color? surface, Color? surfaceRaised, Color? surfaceSubtle, Color? surfacePressed, Color? textPrimary, Color? textSecondary, Color? textTertiary, Color? border, Color? borderStrong, Color? divider, Color? primary, Color? primaryPressed, Color? onPrimary, Color? disabled, Color? onDisabled, Color? focusRing, Color? overlay, Color? photoPlaceholder, Color? error, Color? errorPressed, Color? onError, Color? success, Color? warning}) => FdColors(
    grey0: grey0 ?? this.grey0,
    grey50: grey50 ?? this.grey50,
    grey100: grey100 ?? this.grey100,
    grey200: grey200 ?? this.grey200,
    grey400: grey400 ?? this.grey400,
    grey500: grey500 ?? this.grey500,
    grey700: grey700 ?? this.grey700,
    grey900: grey900 ?? this.grey900,
    grey1000: grey1000 ?? this.grey1000,
    background: background ?? this.background,
    surface: surface ?? this.surface,
    surfaceRaised: surfaceRaised ?? this.surfaceRaised,
    surfaceSubtle: surfaceSubtle ?? this.surfaceSubtle,
    surfacePressed: surfacePressed ?? this.surfacePressed,
    textPrimary: textPrimary ?? this.textPrimary,
    textSecondary: textSecondary ?? this.textSecondary,
    textTertiary: textTertiary ?? this.textTertiary,
    border: border ?? this.border,
    borderStrong: borderStrong ?? this.borderStrong,
    divider: divider ?? this.divider,
    primary: primary ?? this.primary,
    primaryPressed: primaryPressed ?? this.primaryPressed,
    onPrimary: onPrimary ?? this.onPrimary,
    disabled: disabled ?? this.disabled,
    onDisabled: onDisabled ?? this.onDisabled,
    focusRing: focusRing ?? this.focusRing,
    overlay: overlay ?? this.overlay,
    photoPlaceholder: photoPlaceholder ?? this.photoPlaceholder,
    error: error ?? this.error,
    errorPressed: errorPressed ?? this.errorPressed,
    onError: onError ?? this.onError,
    success: success ?? this.success,
    warning: warning ?? this.warning,
  );

  @override
  FdColors lerp(ThemeExtension<FdColors>? other, double t) {
    if (other is! FdColors) return this;
    return FdColors(
      grey0: Color.lerp(grey0, other.grey0, t)!,
      grey50: Color.lerp(grey50, other.grey50, t)!,
      grey100: Color.lerp(grey100, other.grey100, t)!,
      grey200: Color.lerp(grey200, other.grey200, t)!,
      grey400: Color.lerp(grey400, other.grey400, t)!,
      grey500: Color.lerp(grey500, other.grey500, t)!,
      grey700: Color.lerp(grey700, other.grey700, t)!,
      grey900: Color.lerp(grey900, other.grey900, t)!,
      grey1000: Color.lerp(grey1000, other.grey1000, t)!,
      background: Color.lerp(background, other.background, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surfaceRaised: Color.lerp(surfaceRaised, other.surfaceRaised, t)!,
      surfaceSubtle: Color.lerp(surfaceSubtle, other.surfaceSubtle, t)!,
      surfacePressed: Color.lerp(surfacePressed, other.surfacePressed, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textTertiary: Color.lerp(textTertiary, other.textTertiary, t)!,
      border: Color.lerp(border, other.border, t)!,
      borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
      divider: Color.lerp(divider, other.divider, t)!,
      primary: Color.lerp(primary, other.primary, t)!,
      primaryPressed: Color.lerp(primaryPressed, other.primaryPressed, t)!,
      onPrimary: Color.lerp(onPrimary, other.onPrimary, t)!,
      disabled: Color.lerp(disabled, other.disabled, t)!,
      onDisabled: Color.lerp(onDisabled, other.onDisabled, t)!,
      focusRing: Color.lerp(focusRing, other.focusRing, t)!,
      overlay: Color.lerp(overlay, other.overlay, t)!,
      photoPlaceholder: Color.lerp(photoPlaceholder, other.photoPlaceholder, t)!,
      error: Color.lerp(error, other.error, t)!,
      errorPressed: Color.lerp(errorPressed, other.errorPressed, t)!,
      onError: Color.lerp(onError, other.onError, t)!,
      success: Color.lerp(success, other.success, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
    );
  }
}

/// Spacing scale (4px base).
abstract final class FdSpace {
  /// Reset.
  static const double s0 = 0;
  /// Icon-to-text gap inside pills and badges.
  static const double s1 = 4;
  /// Gap between icon and label in buttons; between stacked lines.
  static const double s2 = 8;
  /// Chip row gaps; list row vertical padding (dense).
  static const double s3 = 12;
  /// Mobile screen side margin; card padding; list row padding.
  static const double s4 = 16;
  /// Sheet padding; gap between form fields.
  static const double s5 = 20;
  /// Desktop card padding; gap between sections on mobile.
  static const double s6 = 24;
  /// Desktop page side padding; gap between major sections.
  static const double s8 = 32;
  /// Empty-state padding.
  static const double s10 = 40;
  /// Large separation, top of page headers.
  static const double s12 = 48;
  /// Hero / display spacing.
  static const double s16 = 64;
}

/// Corner radii.
abstract final class FdRadius {
  /// Full-bleed photos, app bars, tab bars, table cells, dividers.
  static const double none = 0;
  /// Small controls: inputs, buttons, chips, status pills, badges, checkboxes, thumbnails, steppers.
  static const double sm = 4;
  /// Containers: cards, sheets (top corners), dialogs, toasts, menus, item photos in rows.
  static const double md = 8;
  /// Only the switch track/thumb, radio, avatar and status dots. Never buttons or cards.
  static const double full = 9999;
}

/// Border widths.
abstract final class FdBorder {
  /// Every border and divider.
  static const double hairline = 1;
  /// New-order card emphasis, active tab indicator, selected radio/offer.
  static const double emphasis = 2;
  /// Focus ring width, with 2px offset.
  static const double focus = 2;
}

/// Fixed component metrics.
abstract final class FdSize {
  /// Minimum touch target on mobile.
  static const double touch = 48;
  /// Primary mobile CTAs (Checkout, Accept order).
  static const double controlLg = 52;
  /// Default buttons and inputs.
  static const double controlMd = 44;
  /// Compact buttons, chips, steppers, table actions (desktop).
  static const double controlSm = 32;
  /// Default icon size; 24px in app bars and tab bars.
  static const double icon = 20;
  /// Mobile top app bar height.
  static const double appBar = 56;
  /// Mobile bottom tab bar height (plus safe area).
  static const double tabBar = 64;
  /// Admin sidebar width.
  static const double sidebar = 240;
  /// Menu item row photo (square).
  static const double thumb = 88;
}

/// Motion durations.
abstract final class FdDuration {
  static const fast = Duration(milliseconds: 120);
  static const base = Duration(milliseconds: 180);
  static const slow = Duration(milliseconds: 240);
}

/// Easing curves.
abstract final class FdEasing {
  static const standard = Cubic(0.2, 0, 0, 1);
  static const exit = Cubic(0.4, 0, 1, 1);
}

/// Type scale. Colour is applied by the theme; numbers use tabular figures via `FdText.num`.
abstract final class FdText {
  static const String family = 'Inter';
  static const List<FontFeature> num = [FontFeature.tabularFigures()];

  /// One per screen at most: order confirmation, big earnings totals, admin KPIs.
  static const display = TextStyle(fontFamily: family, fontSize: 40, height: 1.1, fontWeight: FontWeight.w600, letterSpacing: -0.8);
  /// Admin page titles; restaurant name on the customer menu.
  static const h1 = TextStyle(fontFamily: family, fontSize: 32, height: 1.1875, fontWeight: FontWeight.w600, letterSpacing: -0.48);
  /// Mobile screen titles, sheet titles.
  static const h2 = TextStyle(fontFamily: family, fontSize: 24, height: 1.25, fontWeight: FontWeight.w600, letterSpacing: -0.24);
  /// Section and menu category headers, card titles.
  static const h3 = TextStyle(fontFamily: family, fontSize: 20, height: 1.3, fontWeight: FontWeight.w600, letterSpacing: -0.1);
  /// Default reading text, inputs.
  static const body = TextStyle(fontFamily: family, fontSize: 16, height: 1.5, fontWeight: FontWeight.w400, letterSpacing: 0);
  /// Item names, list row titles, button labels.
  static const bodyStrong = TextStyle(fontFamily: family, fontSize: 16, height: 1.5, fontWeight: FontWeight.w500, letterSpacing: 0);
  /// Secondary lines, descriptions in dense rows, table cells.
  static const small = TextStyle(fontFamily: family, fontSize: 14, height: 1.4286, fontWeight: FontWeight.w400, letterSpacing: 0);
  /// Prices in rows, small buttons, table emphasis.
  static const smallStrong = TextStyle(fontFamily: family, fontSize: 14, height: 1.4286, fontWeight: FontWeight.w500, letterSpacing: 0);
  /// Field labels, chips, status pills, tabs, badges.
  static const label = TextStyle(fontFamily: family, fontSize: 13, height: 1.2308, fontWeight: FontWeight.w500, letterSpacing: 0.13);
  /// Timestamps, helper and error text, chart axes.
  static const caption = TextStyle(fontFamily: family, fontSize: 12, height: 1.3333, fontWeight: FontWeight.w400, letterSpacing: 0.12);
  /// Rewards, totals, stat values. Always with tabular numbers (`.fd-num`).
  static const numericLg = TextStyle(fontFamily: family, fontSize: 28, height: 1.1429, fontWeight: FontWeight.w600, letterSpacing: -0.28, fontFeatures: num);
}
